CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "EEVEE can evolve into one of three\n"
    .string "kinds of POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "There's an e-mail message.\p"
    .string "… … …\p"
    .string "There are three legendary bird\n"
    .string "POKéMON.\p"
    .string "They are ARTICUNO, ZAPDOS, and\n"
    .string "MOLTRES.\p"
    .string "Their whereabouts are unknown.\p"
    .string "We plan to explore the cavern\n"
    .string "close to CERULEAN.\p"
    .string "From: POKéMON RESEARCH TEAM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "An amber pipe!$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_MetronomeGuy::
    .string "Tch-tch-tch!\n"
    .string "I made a cool TM!\p"
    .string "It can cause all kinds of fun!$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_ReceivedTM35Metronome::
    .string "{PLAYER} received TM35.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_Contains_Metronome::
    .string "Tch-tch-tch!\n"
    .string "That's the sound of a METRONOME!\p"
    .string "It tweaks your POKéMON's brain\n"
    .string "into using moves it doesn't know!$"
