CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "POKéMON stat enhancers can be\n"
    .string "bought only here.\p"
    .string "HP UP increases the base HP of a\n"
    .string "POKéMON.\p"
    .string "LYSOZYME raises the base SPECIAL\n"
    .string "stat of one POKéMON.\p"
    .string "ZINC boosts the base SP. DEF stat\n"
    .string "of one POKéMON.\p"
    .string "INDOMETACIN enhances the base SPEED\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "I'm here for POKéMON stat\n"
    .string "enhancers.\p"
    .string "TAURINE increases the base ATTACK\n"
    .string "power.\p"
    .string "BROMHEXINE increases the base DEFENSE\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUGSTORE$"

