ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those MONSTER BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "This POKéMON GYM is always closed.\p"
    .string "I wonder who the LEADER is?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYM's LEADER returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE has no poison,\n"
    .string "but WEEDLE does.\p"
    .string "Watch that your POKéMON aren't\n"
    .string "stabbed by WEEDLE's POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Good grief, Grandpa!\n"
    .string "Sleeping here of all places!\p"
    .string "I'm so sorry. We'll have to\n"
    .string "wait for him to sober up.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "I go shopping in PEWTER CITY\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "VIRIDIAN FOREST when I go.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Hic! Hold it right there!\n"
    .string "Lissen to what I hafta say!\p"
    .string "… Hey! Don' go, I said!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Mmmn… Looks like I was pretty\n"
    .string "drunk then!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a POKéMON,\n"
    .string "the POKéDEX automatically updates\l"
    .string "its data.\p"
    .string "…You don't know how to catch\n"
    .string "a POKéMON?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Mmmn... Looks like I was pretty\n"
    .string "drunk then!\p"
    .string "But my head hurts.\n"
    .string "I'm giving that stuff up!\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Mmmn... Looks like I was pretty\n"
    .string "drunk then!\p"
    .string "But my head hurts.\n"
    .string "I'm giving that stuff up!\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPS\p"
    .string "The battle moves of POKéMON are\n"
    .string "limited by their POWER POINTS, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "POKéMON at a POKéMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYM's doors are locked…$"

ViridianCity_Text_DreamEaterGuy::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this dream about a DROWZEE eating\n"
    .string "my dream.\p"
    .string "What's this?\n"
    .string "Where did this TM come from?\p"
    .string "This is spooky!\n"
    .string "Here, you can have this TM.$"

ViridianCity_Text_ReceivedTM42DreamEater::
    .string "{PLAYER} received TM42.$"

ViridianCity_Text_Contains_DreamEater::
    .string "TM42 contains DREAM EATER…\n"
    .string "…Snore…$"

